services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_DB: 'job-scheduler'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-job-scheduler:latest
    container_name: job-scheduler
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
      - ./eslintrc.json:/usr/src/app/eslintrc.json
      - ./package.json:/usr/src/app/package.json
      - ./package-lock.json:/usr/src/app/package-lock.json
      - ./tsconfig.json:/usr/src/app/tsconfig.json
      - ./tsconfig.build.json:/usr/src/app/tsconfig.build.json
      - ./nest-cli.json:/usr/src/app/nest-cli.json
    environment:
      NODE_ENV: 'loc'
      TZ: 'UTC'
      REDIS_HOST: 'redis'
      REDIS_PORT: '6379'
      DB_USERNAME: 'postgres'
      DB_PASSWORD: 'admin'
      DB_NAME: 'job-scheduler'
      DB_PORT: '5432'
      DB_HOST: 'postgres'
    depends_on:
      - redis
      - postgres

volumes:
  redis-data:
  postgres-data:
